root: ./

structure:
  readme: welcome.md
  summary: summary.md

redirects:
  cli/windows-beta: check/cli/windows-beta.md
  docs: welcome.md
  docs/actions-config: check/actions/config.md
  docs/actions: check/actions/readme.md
  docs/check-cli: check/command-line.md
  docs/check-config: check/config.md
  docs/check-custom-linters: check/custom-linters.md
  docs/check-debugging: check/debugging.md
  docs/check-get-started: check/get-started.md
  docs/check-github-integration: check/github-integration.md
  docs/check-supported-linters: check/supported-linters.md
  docs/check: check/readme.md
  docs/check/github-integration: check/github-integration.md
  docs/ci-debugger: ci-debugger/readme.md
  docs/cli: check/cli/readme.md
  docs/get-started: welcome.md
  docs/getting-started: welcome.md
  docs/github-codespaces: check/cli/github-codespaces.md
  docs/ignoring-issues: check/ignoring-issues.md
  docs/initialize-trunk-in-a-git-repo: check/cli/init-in-a-git-repo.md
  docs/install: check/cli/install-trunk.md
  docs/merge-get-started: merge/get-started.md
  docs/merge: merge/readme.md
  docs/overview: check/cli/readme.md
  docs/plugins: plugins/readme.md
  docs/reference-trunk-yaml: check/reference/trunk-yaml.md
  docs/shell-hooks: check/tools/readme.md#running-tools
  docs/tools: check/tools/readme.md
  docs/trunk-app-for-slack: check/reference/integration-for-slack.md
  docs/upload-check-results: web-app/upload-trunk-check-results.md
  docs/vscode: check/reference/vs-code.md
  docs/what-is-trunk: readme.md
  docs/windows-beta: check/cli/windows-beta.md
  reference/reference-trunk-yaml: check/reference/trunk-yaml.md
  reference/trunk-yaml: check/reference/trunk-yaml.md
