root: ./

structure:
  readme: welcome.md
  summary: summary.md

redirects:
  adminstration: administration/readme.md
  check/performance: check/under-the-hood.md
  check/under-the-hood: check/reference/under-the-hood.md
  check/tools/configuration: check/advanced-setup/tools/configuration.md
  cli/windows-beta: check/advanced-setup/cli/windows-beta.md
  docs: welcome.md
  docs/actions-config: check/actions/config.md
  docs/actions-git-hooks: check/actions/git-hooks.md
  docs/actions: check/advanced-setup/actions/README.md
  docs/check-cli: check/command-line.md
  docs/check-config: check/config.md
  docs/check-custom-linters: check/custom-linters.md
  docs/check-debugging: check/debugging.md
  docs/check-get-started: check/get-started.md
  docs/check-github-integration: check/github-integration.md
  docs/check-supported-linters: check/configuration/supported-linters.md
  docs/check/supported-linters: check/configuration/supported-linters.md
  docs/check: check/readme.md
  docs/check/github-integration: check/github-integration.md
  docs/ci-debugger: ci-debugger/readme.md
  docs/ci: check/check-cloud-ci-integration/readme.md
  docs/cli: check/cli/readme.md
  docs/get-started: welcome.md
  docs/getting-started: welcome.md
  docs/github-app-permissions: administration/github-app-permissions.md
  docs/github-codespaces: check/cli/github-codespaces.md
  docs/ignoring-issues: check/ignoring-issues.md
  docs/initialize-trunk-in-a-git-repo: check/cli/init-in-a-git-repo.md
  docs/install: check/usage.md
  docs/merge-get-started: merge/set-up-trunk-merge.md
  docs/merge-getting-started: merge/set-up-trunk-merge.md
  docs/merge: merge/readme.md
  docs/overview: check/cli/readme.md
  docs/plugins: plugins/readme.md
  docs/reference-trunk-yaml: check/reference/trunk-yaml.md
  docs/shell-hooks: check/tools/readme.md#running-tools
  docs/tools: check/tools/readme.md
  docs/trunk-app-for-slack: check/reference/integration-for-slack.md
  docs/upload-check-results: web-app/upload-trunk-check-results.md
  docs/vscode: check/ide-integration/vs-code.md
  docs/what-is-trunk: readme.md
  docs/windows-beta: check/cli/windows-beta.md
  get-started: welcome.md
  merge-graph: merge/readme.md
  merge-graph/merge: merge/legacy/readme.md
  merge-graph/configuration: merge/configuration.md
  merge-graph/set-up-trunk-merge: merge/readme.md
  merge/getting-started: merge/set-up-trunk-merge.md
  reference/reference-trunk-yaml: check/reference/trunk-yaml.md
  reference/trunk-yaml: check/reference/trunk-yaml.md
