root: ./

structure:
  readme: welcome.md
  summary: summary.md

redirects:
  adminstration: administration/readme.md
  check: code-quality/README.md
  check/cli: code-quality/setup-and-installation/initialize-trunk.md
  check/configuration: cli/configuration/README.md
  check/get-started: code-quality/ci-setup/README.md
  check/usage: code-quality/setup-and-installation/initialize-trunk.md
  check/performance: code-quality/overview/how-does-it-work.md
  check/supported-linters: code-quality/linters/supported/README.md
  check/tools/configuration: cli/configuration/tools.md
  check/under-the-hood: code-quality/overview/how-does-it-work.md
  check/github-integration: code-quality/ci-setup/github-integration.md
  check/configuration/supported: code-quality/linters/supported/README.md
  check/configuration/supported/ansible-lint: code-quality/linters/supported/ansible-lint.md
  check/configuration/supported/codespell: code-quality/linters/supported/codespell.md
  check/configuration/supported/cspell: code-quality/linters/supported/cspell.md
  check/configuration/supported/gitleaks: code-quality/linters/supported/gitleaks.md
  check/configuration/supported/git-diff-check: code-quality/linters/supported/git-diff-check.md
  check/configuration/supported/pre-commit-hooks: code-quality/linters/supported/pre-commit-hooks.md
  check/configuration/supported/pmd: code-quality/linters/supported/pmd.md
  check/configuration/supported/shellcheck: code-quality/linters/supported/shellcheck.md
  check/configuration/supported/shfmt: code-quality/linters/supported/shfmt.md
  check/configuration/supported/buildifier: code-quality/linters/supported/buildifier.md
  check/configuration/supported/iwyu: code-quality/linters/supported/iwyu.md
  check/configuration/supported/pragma-once: code-quality/linters/supported/pragma-once.md
  check/configuration/supported/dotnet-format: code-quality/linters/supported/dotnet-format.md
  check/configuration/supported/circleci: code-quality/linters/supported/circleci.md
  check/configuration/supported/cfnlint: code-quality/linters/supported/cfnlint.md
  check/configuration/supported/checkov: code-quality/linters/supported/checkov.md
  check/configuration/supported/stylelint: code-quality/linters/supported/stylelint.md
  check/configuration/supported/prettier: code-quality/linters/supported/prettier.md
  check/configuration/supported/cue-fmt: code-quality/linters/supported/cue-fmt.md
  check/configuration/supported/hadolint: code-quality/linters/supported/hadolint.md
  check/configuration/supported/dotenv-linter: code-quality/linters/supported/dotenv-linter.md
  check/configuration/supported/actionlint: code-quality/linters/supported/actionlint.md
  check/configuration/supported/gofmt: code-quality/linters/supported/gofmt.md
  check/configuration/supported/gofumpt: code-quality/linters/supported/gofumpt.md
  check/configuration/supported/goimports: code-quality/linters/supported/goimports.md
  check/configuration/supported/gokart: code-quality/linters/supported/gokart.md
  check/configuration/supported/golangci-lint: code-quality/linters/supported/golangci-lint.md
  check/configuration/supported/golines: code-quality/linters/supported/golines.md
  check/configuration/supported/semgrep: code-quality/linters/supported/semgrep.md
  check/configuration/supported/graphql-schema-linter: code-quality/linters/supported/graphql-schema-linter.md
  check/configuration/supported/haml-lint: code-quality/linters/supported/haml-lint.md
  check/configuration/supported/djlint: code-quality/linters/supported/djlint.md
  check/configuration/supported/google-java-format: code-quality/linters/supported/google-java-format.md
  check/configuration/supported/deno: code-quality/linters/supported/deno.md
  check/configuration/supported/eslint: code-quality/linters/supported/eslint.md
  check/configuration/supported/rome: code-quality/linters/supported/rome.md
  check/configuration/supported/detekt: code-quality/linters/supported/detekt.md
  check/configuration/supported/ktlint: code-quality/linters/supported/ktlint.md
  check/configuration/supported/kube-linter: code-quality/linters/supported/kube-linter.md
  check/configuration/supported/stylua: code-quality/linters/supported/stylua.md
  check/configuration/supported/markdownlint: code-quality/linters/supported/markdownlint.md
  check/configuration/supported/remark-lint: code-quality/linters/supported/remark-lint.md
  check/configuration/supported/markdown-link-check: code-quality/linters/supported/markdown-link-check.md
  check/configuration/supported/nixpkgs-fmt: code-quality/linters/supported/nixpkgs-fmt.md
  check/configuration/supported/sort-package-json: code-quality/linters/supported/sort-package-json.md
  check/configuration/supported/perlcritic: code-quality/linters/supported/perlcritic.md
  check/configuration/supported/perltidy: code-quality/linters/supported/perltidy.md
  check/configuration/supported/oxipng: code-quality/linters/supported/oxipng.md
  check/configuration/supported/prisma: code-quality/linters/supported/prisma.md
  check/configuration/supported/buf: code-quality/linters/supported/buf.md
  check/configuration/supported/clang-format: code-quality/linters/supported/clang-format.md
  check/configuration/supported/clang-tidy: code-quality/linters/supported/clang-tidy.md
  check/configuration/supported/autopep8: code-quality/linters/supported/autopep8.md
  check/configuration/supported/bandit: code-quality/linters/supported/bandit.md
  check/configuration/supported/black: code-quality/linters/supported/black.md
  check/configuration/supported/flake8: code-quality/linters/supported/flake8.md
  check/configuration/supported/isort: code-quality/linters/supported/isort.md
  check/configuration/supported/mypy: code-quality/linters/supported/mypy.md
  check/configuration/supported/pylint: code-quality/linters/supported/pylint.md
  check/configuration/supported/pyright: code-quality/linters/supported/pyright.md
  check/configuration/supported/yapf: code-quality/linters/supported/yapf.md
  check/configuration/supported/ruff: code-quality/linters/supported/ruff.md
  check/configuration/supported/sourcery: code-quality/linters/supported/sourcery.md
  check/configuration/supported/renovate: code-quality/linters/supported/renovate.md
  check/configuration/supported/brakeman: code-quality/linters/supported/brakeman.md
  check/configuration/supported/rubocop: code-quality/linters/supported/rubocop.md
  check/configuration/supported/rufo: code-quality/linters/supported/rufo.md
  check/configuration/supported/standardrb: code-quality/linters/supported/standardrb.md
  check/configuration/supported/clippy: code-quality/linters/supported/clippy.md
  check/configuration/supported/rustfmt: code-quality/linters/supported/rustfmt.md
  check/configuration/supported/scalafmt: code-quality/linters/supported/scalafmt.md
  check/configuration/supported/dustilock: code-quality/linters/supported/dustilock.md
  check/configuration/supported/nancy: code-quality/linters/supported/nancy.md
  check/configuration/supported/osv-scanner: code-quality/linters/supported/osv-scanner.md
  check/configuration/supported/tfsec: code-quality/linters/supported/tfsec.md
  check/configuration/supported/trivy: code-quality/linters/supported/trivy.md
  check/configuration/supported/trufflehog: code-quality/linters/supported/trufflehog.md
  check/configuration/supported/terrascan: code-quality/linters/supported/terrascan.md
  check/configuration/supported/sqlfluff: code-quality/linters/supported/sqlfluff.md
  check/configuration/supported/sqlfmt: code-quality/linters/supported/sqlfmt.md
  check/configuration/supported/sql-formatter: code-quality/linters/supported/sql-formatter.md
  check/configuration/supported/svgo: code-quality/linters/supported/svgo.md
  check/configuration/supported/stringslint: code-quality/linters/supported/stringslint.md
  check/configuration/supported/swiftlint: code-quality/linters/supported/swiftlint.md
  check/configuration/supported/swiftformat: code-quality/linters/supported/swiftformat.md
  check/configuration/supported/terraform: code-quality/linters/supported/terraform.md
  check/configuration/supported/tflint: code-quality/linters/supported/tflint.md
  check/configuration/supported/terragrunt: code-quality/linters/supported/terragrunt.md
  check/configuration/supported/txtpbfmt: code-quality/linters/supported/txtpbfmt.md
  check/configuration/supported/taplo: code-quality/linters/supported/taplo.md
  check/configuration/supported/yamllint: code-quality/linters/supported/yamllint.md
  check/configuration/supported/biome: code-quality/linters/supported/biome.md
  check/configuration/supported/markdown-table-prettify: code-quality/linters/supported/markdown-table-prettify.md
  check/configuration/supported/psscriptanalyzer: code-quality/linters/supported/psscriptanalyzer.md
  check/configuration/supported/cmake-format: code-quality/linters/supported/cmake-format.md
  check/configuration/supported/dart: code-quality/linters/supported/dart.md
  check/configuration/supported/opa: code-quality/linters/supported/opa.md
  check/configuration/supported/phpstan: code-quality/linters/supported/phpstan.md
  check/configuration/supported/regal: code-quality/linters/supported/regal.md
  check/configuration/supported/tofu: code-quality/linters/supported/tofu.md
  check/configuration/supported/vale: code-quality/linters/supported/vale.md
  check/configuration/supported/php-cs-fixer: code-quality/linters/supported/php-cs-fixer.md
  cli/windows-beta: cli/compatibility.md
  docs: welcome.md
  docs/actions-config: check/actions/config.md
  docs/actions-git-hooks: check/actions/git-hooks.md
  docs/actions: check/advanced-setup/actions/readme.md
  docs/check-cli: check/command-line.md
  docs/check-config: check/config.md
  docs/check-custom-linters: check/custom-linters.md
  docs/check-debugging: code-quality/debugging.md
  docs/check-get-started: check/get-started.md
  docs/check-github-integration: check/github-integration.md
  docs/check-supported-linters: check/configuration/supported/readme.md
  docs/check: code-quality/README.md
  docs/check/github-integration: code-quality/ci-setup/github-integration.md
  docs/ci-debugger: ci-debugger/readme.md
  docs/ci: check/check-cloud-ci-integration/readme.md
  docs/cli: check/cli/readme.md
  docs/get-started: welcome.md
  docs/getting-started: welcome.md
  docs/github-app-permissions: administration/github-app-permissions.md
  docs/github-codespaces: check/cli/github-codespaces.md
  docs/ignoring-issues: check/ignoring-issues.md
  docs/initialize-trunk-in-a-git-repo: check/cli/init-in-a-git-repo.md
  docs/install: check/usage.md
  docs/merge-get-started: merge/set-up-trunk-merge.md
  docs/merge-getting-started: merge/set-up-trunk-merge.md
  docs/merge: merge/readme.md
  docs/overview: check/cli/readme.md
  docs/plugins: plugins/readme.md
  docs/reference-trunk-yaml: cli/configuration/README.md
  docs/shell-hooks: check/tools/readme.md#running-tools
  docs/tools: check/tools/readme.md
  docs/trunk-app-for-slack: check/reference/integration-for-slack.md
  docs/upload-check-results: web-app/upload-trunk-check-results.md
  docs/vscode: code-quality/ide-integration/vscode
  docs/what-is-trunk: readme.md
  docs/windows-beta: check/cli/windows-beta.md
  flaky-tests/generating-junit-reports: flaky-tests/frameworks/readme.md
  get-started: welcome.md
  merge-graph: merge/readme.md
  merge-graph/configuration: merge/configuration.md
  merge-graph/merge: merge/legacy/readme.md
  merge-graph/set-up-trunk-merge: merge/readme.md
  merge/getting-started: merge/set-up-trunk-merge.md
  reference/reference-trunk-yaml: cli/configuration/README.md
  reference/trunk-yaml: cli/configuration/README.md
  test-analytics: flaky-tests/readme.md
  test-analytics/ci-providers: flaky-tests/ci-providers/readme.md
  test-analytics/ci-providers/buildkite-quickstart: flaky-tests/ci-providers/buildkite-quickstart.md
  test-analytics/ci-providers/circleci-quickstart: flaky-tests/ci-providers/circleci-quickstart.md
  test-analytics/ci-providers/github-actions-quickstart: flaky-tests/ci-providers/github-actions-quickstart.md
  test-analytics/ci-providers/gitlab: flaky-tests/ci-providers/gitlab.md
  test-analytics/ci-providers/other-ci-providers-quickstart: flaky-tests/ci-providers/other-ci-providers-quickstart.md
  test-analytics/ci-providers/semaphore-ci-quickstart: flaky-tests/ci-providers/semaphore-ci-quickstart.md
  test-analytics/frameworks: flaky-tests/frameworks/readme.md
  test-analytics/frameworks/android: flaky-tests/frameworks/android.md
  test-analytics/frameworks/cargo-nextest: flaky-tests/frameworks/cargo-nextest.md
  test-analytics/frameworks/cypress: flaky-tests/frameworks/cypress.md
  test-analytics/frameworks/jasmine: flaky-tests/frameworks/jasmine.md
  test-analytics/frameworks/jest: flaky-tests/frameworks/jest.md
  test-analytics/frameworks/minitest: flaky-tests/frameworks/minitest.md
  test-analytics/frameworks/mocha: flaky-tests/frameworks/mocha.md
  test-analytics/frameworks/playwright: flaky-tests/frameworks/playwright.md
  test-analytics/frameworks/pytest: flaky-tests/frameworks/pytest.md
  test-analytics/frameworks/rspec: flaky-tests/frameworks/rspec.md
  test-analytics/frameworks/swift-testing: flaky-tests/frameworks/swift-testing.md
  test-analytics/frameworks/xctest: flaky-tests/frameworks/xctest.md
  test-analytics/github-pull-request-comments: flaky-tests/github-pull-request-comments.md
  runtimes: cli/configuration/runtimes.md
  plugins: cli/configuration/plugins/README.md
  ci/get-started/github-integration: code-quality/ci-setup/github-integration.md
  code-quality/usage: code-quality/setup-and-installation/initialize-trunk.md
  code-quality/ci/get-started: code-quality/ci-setup/README.md
  code-quality/ci/get-started/github-integration: code-quality/ci-setup/github-integration.md
  code-quality/configuration/debugging: code-quality/debugging.md
  check/check-cloud-ci-integration/get-started/github-integration: code-quality/ci-setup/github-integration.md
  flaky-tests/ci-providers/buildkite-quickstart: flaky-tests/get-started/ci-providers/buildkite-quickstart.md
