root: ./

structure:
  readme: welcome.md
  summary: summary.md

redirects:
  adminstration: administration/readme.md
  check/performance: check/under-the-hood.md
  check/supported-linters: check/configuration/supported/readme.md
  check/tools/configuration: check/advanced-setup/tools/configuration.md
  check/under-the-hood: check/reference/under-the-hood.md
  cli/windows-beta: check/advanced-setup/cli/windows-beta.md
  docs: welcome.md
  docs/actions-config: check/actions/config.md
  docs/actions-git-hooks: check/actions/git-hooks.md
  docs/actions: check/advanced-setup/actions/readme.md
  docs/check-cli: check/command-line.md
  docs/check-config: check/config.md
  docs/check-custom-linters: check/custom-linters.md
  docs/check-debugging: check/debugging.md
  docs/check-get-started: check/get-started.md
  docs/check-github-integration: check/github-integration.md
  docs/check-supported-linters: check/configuration/supported/readme.md
  docs/check: check/readme.md
  docs/check/github-integration: check/github-integration.md
  docs/ci-debugger: ci-debugger/readme.md
  docs/ci: check/check-cloud-ci-integration/readme.md
  docs/cli: check/cli/readme.md
  docs/get-started: welcome.md
  docs/getting-started: welcome.md
  docs/github-app-permissions: administration/github-app-permissions.md
  docs/github-codespaces: check/cli/github-codespaces.md
  docs/ignoring-issues: check/ignoring-issues.md
  docs/initialize-trunk-in-a-git-repo: check/cli/init-in-a-git-repo.md
  docs/install: check/usage.md
  docs/merge-get-started: merge/set-up-trunk-merge.md
  docs/merge-getting-started: merge/set-up-trunk-merge.md
  docs/merge: merge/readme.md
  docs/overview: check/cli/readme.md
  docs/plugins: plugins/readme.md
  docs/reference-trunk-yaml: check/reference/trunk-yaml.md
  docs/shell-hooks: check/tools/readme.md#running-tools
  docs/tools: check/tools/readme.md
  docs/trunk-app-for-slack: check/reference/integration-for-slack.md
  docs/upload-check-results: web-app/upload-trunk-check-results.md
  docs/vscode: check/ide-integration/vs-code.md
  docs/what-is-trunk: readme.md
  docs/windows-beta: check/cli/windows-beta.md
  flaky-tests/generating-junit-reports: flaky-tests/frameworks/readme.md
  get-started: welcome.md
  merge-graph: merge/readme.md
  merge-graph/configuration: merge/configuration.md
  merge-graph/merge: merge/legacy/readme.md
  merge-graph/set-up-trunk-merge: merge/readme.md
  merge/getting-started: merge/set-up-trunk-merge.md
  reference/reference-trunk-yaml: check/reference/trunk-yaml.md
  reference/trunk-yaml: check/reference/trunk-yaml.md
  test-analytics: flaky-tests/readme.md
  test-analytics/ci-providers: flaky-tests/ci-providers/readme.md
  test-analytics/ci-providers/buildkite-quickstart: flaky-tests/ci-providers/buildkite-quickstart.md
  test-analytics/ci-providers/circleci-quickstart: flaky-tests/ci-providers/circleci-quickstart.md
  test-analytics/ci-providers/github-actions-quickstart: flaky-tests/ci-providers/github-actions-quickstart.md
  test-analytics/ci-providers/gitlab: flaky-tests/ci-providers/gitlab.md
  test-analytics/ci-providers/other-ci-providers-quickstart: flaky-tests/ci-providers/other-ci-providers-quickstart.md
  test-analytics/ci-providers/semaphore-ci-quickstart: flaky-tests/ci-providers/semaphore-ci-quickstart.md
  test-analytics/frameworks: flaky-tests/frameworks/readme.md
  test-analytics/frameworks/android: flaky-tests/frameworks/android.md
  test-analytics/frameworks/cargo-nextest: flaky-tests/frameworks/cargo-nextest.md
  test-analytics/frameworks/cypress: flaky-tests/frameworks/cypress.md
  test-analytics/frameworks/jasmine: flaky-tests/frameworks/jasmine.md
  test-analytics/frameworks/jest: flaky-tests/frameworks/jest.md
  test-analytics/frameworks/minitest: flaky-tests/frameworks/minitest.md
  test-analytics/frameworks/mocha: flaky-tests/frameworks/mocha.md
  test-analytics/frameworks/playwright: flaky-tests/frameworks/playwright.md
  test-analytics/frameworks/pytest: flaky-tests/frameworks/pytest.md
  test-analytics/frameworks/rspec: flaky-tests/frameworks/rspec.md
  test-analytics/frameworks/swift-testing: flaky-tests/frameworks/swift-testing.md
  test-analytics/frameworks/xctest: flaky-tests/frameworks/xctest.md
  test-analytics/github-pull-request-comments: flaky-tests/github-pull-request-comments.md
